workflows:
  android_debug_apk:
    name: Android Debug APK
    max_build_duration: 60
    environment:
      node: 18
      java: 17
      vars:
        ANDROID_PROJECT_DIR: "android"
      groups: []
      flutter: stable
    scripts:
      - name: Install Node deps
        script: |
          npm install
      - name: Build web (Vite)
        script: |
          npm run build
      - name: Ensure Capacitor + Android
        script: |
          npx cap --version
          if [ ! -d android ]; then npx cap add android; fi
          npx cap sync android
      - name: Make gradlew executable
        script: |
          cd android && chmod +x gradlew
      - name: Build APK (debug)
        script: |
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
