workflows:
  android_debug:
    name: Android Debug APK
    environment:
      node: 18
      java: 17
    scripts:
      - npm install
      - npx cap sync android
      - cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
